[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -M virt -cpu rv64 -m 64M -smp 1 -nographic -bios default -kernel"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
]
